### ISSUE TITLE
Handling payments 'placed in review' in Stripe Radar

### ISSUE THREAD

**Issue by ameyers** [vendrhub/vendr-payment-provider-stripe#10]
A number of rules have been set up and configured in Stripe Radar to place payments 'in review', one example being 
`::customer:billingZipCode:: != :billing_address_postal_code:`. Payment is set to `capture_method=Automatic` the transaction is captured, and the order is passed back to Vendr and then proceeding through Vendr as Captured.

Stripe still processes payments normally when they meet a review rule’s criteria. 

The reasoning behind those rules being configured in the 'in review' section of Stripe Radar and not the 'Block' is so that payments can be manually checked. We don't necessarily want to block the payment entirely as this may result in too many genuine orders being blocked. Instead, we just want to be able to slow down the process so that manual checks can be performed and either accepted or rejected.

So the question is, is it possible to detect if the payment has been placed into review based on the response from Stripe? I guess this depends if 'checkout.session.completed' event holds that data?

**Comment by mattbrailsford** [comment]
It's a qood question and defo something we can look at to see what info is present.

I guess it's knowing what we want the process to be here? Should the order still finalize but potentially be set to the status `PendingExternalSystem` and then attempt to become `Captured` once it passes review. If it fails review, I guess it would either need to become `Canceled` or `Error`. Either way, Vendr will still currently send out an Order Confirmation email and will direct the user to the confirmation page, so I'm not sure we could change this flow too much (without it being a big breaking change). 

Saying this, as this is just stripe we are talking about right now, maybe the later bit just needs to be a custom implementation at the moment whereby if the order is in `PendingExternalSystem` at the point of sending the confirmation email, you can update that email template to say something like "Payment is being reviewed" then you could setup some custom emails to be sent when the payment changes from `Pending` to one of the other status to send a follow up email (successful payment, goods are on the way or canceled, your payment failed and your order has been canceled).

I think we can at least first look at what radar info we receive and see if we can set the payment status accordingly.

**Comment by ameyers** [comment]
The process you describe sounds about right to me. Order finalises, status set to `PendingExternalSystem` then attempts to become `Captured` once the reviewer has accepted the payment. Then if it fails the status just moved to `Error` or `Cancelled` all makes sense.

I see what you mean about the Order Confirmation page and Order Confirmation email flow - the order has been processed and the payment has been captured it's just that the payment has been placed in review, so it wouldn't necessarily result in the customer being taken to the Order Error page. Am I right in thinking the Order Confirmation email is handled and sent within Vendr Core?

**Comment by ameyers** [comment]
From a quick look at the Stripe API docs, it looks like there are two places to draw the data I think we might need...

**Retrieving a PaymentIntent**

[Review object on PaymentIntent](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-review)
[Review object](https://stripe.com/docs/api/radar/reviews/retrieve)

**Retrieving a Charge**

[Outcome object](https://stripe.com/docs/api/charges/object#charge_object-outcome)

I can see that on payments placed 'in review' both of those are populated

**Comment by mattbrailsford** [comment]
So I think I've resolved this in commit 1ef03c2c752e4b1640d13f897d8c2be03a712de3.

Ultimately, it looks like a payment intent object has a `Review` object on it and if this has it's `Open` property set to true, we can just return a `Pending` payment status. Within Stripe you'd then need to handle those payments where your options are to `Approve` it, in which case Vendr gets notified and sets it to `Captured` or `Authorized` depending on how you have the payment provider, or if you `Refund` the transaction, it will appear in Vendr as `Refunded`.

In order to get notified of the review being updated you'll need to update your webhook configuration in stripe to also subscribe to the `review.closed` event. With that set up, Vendr should auto update when changes are made to the review.

If you want to test this, it is on our unstable feed https://nuget.outfield.digital/unstable/vendr/v3/index.json version 1.2.2-beta0001

As mentioned earlier, if you need to notify your customer, you'll need to use Vendr events to listen for order transaction info updates and when an order moves from `Pending` to some other status, you'll then need to trigger the sending of a custom email template.

**Comment by mattbrailsford** [comment]
This has now been released.
