### ISSUE TITLE
Question - does this help at all if not using Stripe Checkout

### ISSUE THREAD

**Issue by drpeck** [vendrhub/vendr-payment-provider-stripe#5]
I'm trying to get my head around Vendr & Stripe from a place of extreme ignorance.

Assuming I've not missed something, this Stripe Payment Provider works only via a redirect to https://checkout.stripe.com. I'd hoped to handle Stripe using stripe.js, such that the payment form is rendered within my site, and the payment capture happens as a result of a clientside API call (e.g.  https://stripe.com/docs/payments/accept-a-payment?integration=elements).

If I've understood [the documentation](https://vendr.net/docs/core/1-3-0/key-concepts/payment-providers/) correctly then I should be able to create a new payment provider to support my preferred approach. However before I go too far down this road can I please check:

1. I should consider vendr-payment-provider-stripe of no use
2. that you know of know reason why want I wish to achieve isn't possible
3. that you don't know of anyone that might have already undertaken this work.

I note that the diagram below has the payment form within the Payment Gateway.
![image](https://user-images.githubusercontent.com/1196047/98682097-6cd7a500-235b-11eb-8960-9a1e18d9cacf.png)

**Comment by mattbrailsford** [comment]
Hi @drpeck 

What you want to achieve is possible, and this is the way that things worked in TC, using the inline approach. From our experience as a product maintainer though, the overhead of implementing this approach put too much burden on developers which lead to a lot of questions and support requests. Ultimately it wasn't very friendly and so the newer, redirect approach became much simpler for us to explain and works well enough for most people.

As I say though, yes, your are entirely able to do this if you wish to implement it yourself.

In answer to your questions.

1. Not entirely. I think quite a bit of it could be reused, especially around the callback code for handling webhooks. 
2. It's entirely possible
3. I don't know anyone currently who as looked to undertake this, no.

Ultimately, that diagram is to cover the most likely scenario, and the one we find easiest to recommend / explain for others to implement. Redirect approach payment providers usually follow a similar pattern, where inline ones don't, and so it's harder to document generically.

For stripe though, and how we did in TC was to capture a "Payment Form" URL in the provider settings which was the URL of the local site which had the Stripe inline code implemented on. The payment provider would then do it's usual code, but rather than redirecting away to a 3rd party, would redirect to a page on your site with your custom stripejs form on. On this page, you'd then do what you need to do client side, and when you needed to communicate back to the server, you would call the payment providers callbackUrl passing in query parameters for it to figure out what action is being performed.

Generally, you can think of the ProcessCallback method as just being a generic request handler. You can look at the querystring and decide what action to perform, whether than is capturing the order from the front end, or handling the webhook response from Stripe. For you, you'd want to use it from the client side to perform the server site stripe interactions you need to perform.

I think this should be enough info for an initial point for you to investigate.

I'm gonna close this issue as generally Questions should be asked on the forums, but feel free to reply and I'll still get the notifications to help 👍

**Comment by drpeck** [comment]
Lovely response. Thank you.
